name: Demo Concurrency and timeout

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo docker details
      run: docker info

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker hello world
      run: |
        sleep 600s
        docker run hello-world
