name: Demo Concurrency and timeout

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo docker details
      run: docker info

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: production-group
      cancel-in-progress: true
    steps:
    - name: Docker hello world
      timeout-minutes: 1 #this should timeout the workflow since there is a sleep of 10 mins below
      run: |
        sleep 600s
        docker run hello-world
