name: Matrix demo

on:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:  
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Docker Info
      run: docker info
  
    - name: Docker hello world
      run: docker run ${{ matrix.images }}
