name: Matrix demo

on:
  workflow_dispatch:

jobs:
  docker:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:  
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude: 
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20-04
    runs-on: ${{ matrix.os }}
    steps:
    - name: Docker Info
      run: docker info
  
    - name: Docker hello world
      run: docker run ${{ matrix.images }}
